# Generated by Django 3.2.16 on 2023-06-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation', models.CharField(max_length=200)),
                ('fulfilled_strategies', models.ManyToManyField(blank=True, related_name='fulfilled_series', to='home.StrategyCard')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyDeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('strategies', models.ManyToManyField(blank=True, related_name='deck_strategies', to='home.StrategyCard')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('strategies', models.ManyToManyField(blank=True, related_name='strategy_series', to='home.StrategyCard')),
            ],
        ),
    ]
