# Generated by Django 3.2.16 on 2023-06-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategycard',
            name='cover',
            field=models.CharField(default='empty cover', max_length=200),
        ),
        migrations.AddField(
            model_name='strategycard',
            name='explanation',
            field=models.CharField(default='empty explanation', max_length=2000),
        ),
        migrations.AddField(
            model_name='strategycard',
            name='footnote',
            field=models.CharField(default='empty footnote', max_length=200),
        ),
        migrations.AddField(
            model_name='strategycard',
            name='signalType',
            field=models.CharField(default='empty signal type', max_length=200),
        ),
        migrations.AddField(
            model_name='strategycard',
            name='strategyType',
            field=models.CharField(default='empty strategyType', max_length=200),
        ),
        migrations.AlterField(
            model_name='strategycard',
            name='title',
            field=models.CharField(default='empty title', max_length=200),
        ),
    ]
