# Generated by Django 3.2.16 on 2023-06-19 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230615_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filterStrategicStop', models.BooleanField(default=True)),
                ('filterCandlestickPattern', models.BooleanField(default=True)),
                ('filterIndexValue', models.BooleanField(default=True)),
                ('filterIndexTrend', models.BooleanField(default=True)),
                ('filterBuy', models.BooleanField(default=True)),
                ('filterSell', models.BooleanField(default=True)),
                ('filterWait', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=2000)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('note_type', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell'), ('transaction series', 'transaction series'), ('free', 'free')], default='free', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='strategycard',
            name='signalType',
        ),
        migrations.RemoveField(
            model_name='strategycard',
            name='strategyType',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='annotation',
        ),
        migrations.AddField(
            model_name='strategycard',
            name='signal_type',
            field=models.CharField(choices=[('candlestick pattern', 'candlestick pattern'), ('index value', 'index value'), ('index trend', 'index trend'), ('strategic stop', 'strategic stop')], default='free', max_length=200),
        ),
        migrations.AddField(
            model_name='transaction',
            name='actionType',
            field=models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], default='buy', max_length=200),
        ),
        migrations.AddField(
            model_name='transaction',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.DeleteModel(
            name='Series',
        ),
        migrations.AddField(
            model_name='transactionseries',
            name='adoptedStrategyCard',
            field=models.ManyToManyField(blank=True, related_name='strategy_series', to='home.StrategyCard'),
        ),
        migrations.AddField(
            model_name='transactionseries',
            name='adoptedStrategyDeck',
            field=models.ManyToManyField(blank=True, related_name='strategy_series', to='home.StrategyDeck'),
        ),
        migrations.AddField(
            model_name='transactionseries',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.note'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.note'),
        ),
    ]
