# Generated by Django 3.2.16 on 2023-06-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20230619_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategycard',
            name='cover',
            field=models.CharField(default='question-mark.jpg', max_length=200),
        ),
    ]
