# Generated by Django 3.2.16 on 2023-06-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_strategycard_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategycard',
            name='strategy_type',
            field=models.CharField(choices=[('candlestick pattern', 'candlestick pattern'), ('index value', 'index value'), ('index trend', 'index trend'), ('strategic stop', 'strategic stop')], default='free', max_length=200),
        ),
        migrations.AlterField(
            model_name='strategycard',
            name='signal_type',
            field=models.CharField(choices=[('buy', 'buy'), ('sell', 'sell'), ('wait', 'wait')], default='free', max_length=200),
        ),
    ]
