# Generated by Django 3.2.16 on 2023-06-20 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20230620_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategycard',
            old_name='signal_type',
            new_name='signalType',
        ),
        migrations.RenameField(
            model_name='strategycard',
            old_name='strategy_type',
            new_name='strategyType',
        ),
    ]
