# Generated by Django 3.2.16 on 2023-07-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_strategydeck_is_current'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsBuildingDeck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_building_deck', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Filter',
        ),
    ]
