# Generated by Django 3.2.16 on 2023-07-04 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20230704_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategydeck',
            name='is_current',
        ),
        migrations.CreateModel(
            name='CurrentDeck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('is_current', models.BooleanField(default=True)),
                ('strategies', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.strategycard')),
            ],
        ),
    ]
