# Generated by Django 3.2.16 on 2023-07-04 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_strategydeck_strategies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentdeck',
            name='strategies',
        ),
        migrations.AddField(
            model_name='strategydeck',
            name='strategies',
            field=models.ManyToManyField(blank=True, related_name='deck_strategies', to='home.StrategyCard'),
        ),
    ]
