# Generated by Django 3.2.16 on 2023-07-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20230704_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentdeck',
            name='counter',
            field=models.BigIntegerField(default=0),
        ),
    ]
