# Generated by Django 3.2.16 on 2023-07-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_currentdeck_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentdeck',
            name='counter',
            field=models.BigIntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='strategydeck',
            name='strategies',
        ),
        migrations.AddField(
            model_name='strategydeck',
            name='strategies',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
