# Generated by Django 3.2.16 on 2023-07-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20230711_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentdeck',
            name='strategies',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
